### ISSUE TITLE
如何使用？为什么格式不一样？

### ISSUE THREAD

**Issue by AndACat** [lartpang/PySODEvalToolkit#10]
![image](https://user-images.githubusercontent.com/44843774/166104730-51aa16c7-fb65-43ba-85bb-696ef1894571.png)

**Comment by lartpang** [comment]
@AndACat 
这个仅仅是路径而已，你对应好而已。我自己本地使用的时候是稍微更复杂些的，对于分享出来的代码是经过一些简化后的，毕竟实际上使用可能并不需要太复杂的目录层次。

**Comment by lartpang** [comment]
@AndACat 欢迎使用最新版，有问题可以继续交流。
