### ISSUE TITLE
教程写的不明不白 一点都不好用 果断弃坑。

### ISSUE THREAD

**Issue by AndACat** [lartpang/PySODEvalToolkit#11]
教程写的不明不白 一点都不好用 果断弃坑。
2023 03 06更
代码挺好用的 欢迎大家使用

**Comment by lartpang** [comment]
@AndACat 由于本项目脱胎于本人实际用于评估各种代码时的一些基础工具，后续加工整理而成，可能使用逻辑有些和普通工具不太一样。欢迎指出不足指出哦！

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@AndACat  欢迎大佬你写一份清清楚楚、明明白白的代码给小白们使用。

**Comment by lmolhw5252** [comment]
请问npy文件从哪生成？

**Comment by lartpang** [comment]
> 请问npy文件从哪生成？

可以看这里的使用说明：

https://github.com/lartpang/PySODEvalToolkit#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by lartpang** [comment]
@AndACat 
@lmolhw5252 

最近更新了几版内容，感兴趣的话可以再试试。
