### ISSUE TITLE
我执行plot.py，生成的pdf中没有曲线生成

### ISSUE THREAD

**Issue by awk333** [lartpang/PySODEvalToolkit#12]
![image](https://user-images.githubusercontent.com/44765875/184322328-ffc91c1e-5d1a-4773-a088-78d35174fdf8.png)
麻烦看看是什么问题？

**Comment by awk333** [comment]
> ![image](https://user-images.githubusercontent.com/44765875/184322328-ffc91c1e-5d1a-4773-a088-78d35174fdf8.png) 麻烦看看是什么问题？

将curve_drawer.py中的这两行注掉就好了
ax.set_xlim((min(x_ticks), max(x_ticks)))
ax.set_ylim((min(y_ticks), max(x_ticks)))

**Comment by lartpang** [comment]
@awk333 

看起来应该是因为这里的x_ticks和y_ticks不适合你的数据。这两个参数可以考虑按照你的实际数据进行一下调整。

https://github.com/lartpang/PySODEvalToolkit/blob/a5cef120de1d7f18bdbfd03fe5406df9b5e159bd/plot.py#L102-L115
