### ISSUE TITLE
关于F-measure的一些问题

### ISSUE THREAD

**Issue by Ayews** [lartpang/PySODEvalToolkit#14]
作者您好！我在使用此工具去eval一项别的工作提供的预测图时，发现工具给出的F-measure的数值与那项工作文中描述的不一致，它的要高一些，因此产生了一些疑惑。那篇工作名为：《Pyramid Grafting Network for One-Stage High Resolution Saliency Detection》，他在文中描述F-measure为max F-m。
我的问题是，您的代码中在实现F-m时是怎么获得max F-m的？这里的max F-m是针对单张图片的，还是整个数据集的？对于我提到的这项工作中，他用到的F-m在数值上略高这件事您有什么头绪吗？我有点没弄懂，恳请您能够指点一二，非常感谢！

**Comment by Ayews** [comment]
我看了您在另一个issue里的回答，我猜测上面那项工作可能是对每张图片做的max F-measure

**Comment by Ayews** [comment]
我看了您在其他issue里的回答，对于如何获取F-m这个问题我已有所了解，感觉实现的还是很合理的，现在就是比较好奇他这个为什么会高一些，他的代码里也没提供评价方法，不知道怎么做到的。

**Comment by lartpang** [comment]
@Ayews 主要会引起计算差异的是划分阈值的方式。有的会划分成255个值。我这里是256个值。这部分代码可见我实现的指标仓库：

https://github.com/lartpang/PySODMetrics/blob/b733575412eee0b129df074d908e47ac8c7e0054/py_sod_metrics/sod_metrics.py#L107-L109

当然也可能会有其他的一些隐晦的差异。

所以对于SOD的一系列任务而言，大家都会提供自己的预测map，之后使用统一的指标代码进行测试。

这也正是我开发这个指标库的初衷，希望可以帮助大家可以统一一下使用的指标。

**Comment by Ayews** [comment]
我了解了，感谢您的回复。
