### ISSUE TITLE
配置信息

### ISSUE THREAD

**Issue by Tianyu100** [lartpang/PySODEvalToolkit#15]
你好，不太理解config_method_py_exampl.py模型是怎么放置的，请问可以给出如何放置位置的截图吗，<your_methods_path>是放模型训练好的权重，还是模型结构呢

**Comment by lartpang** [comment]
@Tianyu100 
建议直接使用json配置文件，这样就省去了额外转换的步骤。

https://github.com/lartpang/PySODEvalToolkit/blob/master/examples/config_method_json_example.json

- `path`表示的是对于数据集预测的文件夹。
- `suffix`表示的是预测的图片的名字相对于真值无后缀名字的后缀，假如预测为`abc_def.png`，而真值为`abc.png`，那这里可以写`_def.png`。
