### ISSUE TITLE
存放图片

### ISSUE THREAD

**Issue by lartpang** [lartpang/PySODEvalToolkit#16]
## PR Curves

![caver-pr](https://user-images.githubusercontent.com/26847524/227249768-a41ef076-6355-4b96-a291-fc0e071d9d35.jpg)

## F-measure Curves

![caver-fm](https://user-images.githubusercontent.com/26847524/227249746-f61d7540-bb73-464d-bccf-9a36323dec47.jpg)

## E-measure Curves

![caver-em](https://user-images.githubusercontent.com/26847524/227249727-8323d5cf-ddd7-427b-8152-b8f47781c4e3.jpg)

**Comment by npuprince** [comment]
你好作者，请问哪个参数是控制 label 在右侧单独显示而不是在曲线图上显示？

**Comment by lartpang** [comment]
@npuprince 

https://github.com/lartpang/PySODEvalToolkit/blob/a52dbccb90ec3da8f52a6e0b97b055e1d27b6319/plot.py#L58
