### ISSUE TITLE
python plot.py报错

### ISSUE THREAD

**Issue by WkangLiu** [lartpang/PySODEvalToolkit#18]
在运行完python eval.py后生成了curves.npy,运行python plot.py报错
```
Traceback (most recent call last):
  File "/data1/lkw/PySODEvalToolkit/plot.py", line 132, in <module>
    main(args)
  File "/data1/lkw/PySODEvalToolkit/plot.py", line 98, in main
    draw_curves.draw_curves(
  File "/data1/lkw/PySODEvalToolkit/metrics/draw_curves.py", line 145, in draw_curves
    y_data = method_results["precision"]
KeyError: 'precision'
```
请问这可能是什么错误？

**Comment by lartpang** [comment]
@WkangLiu 

这应该是您第一次评估的时候没有指定precision这个指标。如果您想绘制precision-recall曲线的时候，请指定这两个指标。

您是参考这里 https://github.com/lartpang/PySODEvalToolkit#%E4%B8%80%E4%B8%AA%E5%9F%BA%E6%9C%AC%E7%9A%84%E6%89%A7%E8%A1%8C%E6%B5%81%E7%A8%8B 的示例么？我这里似乎漏了一些内容。

**Comment by lartpang** [comment]
@WkangLiu 

这应该是您第一次评估的时候没有指定precision这个指标。如果您想绘制precision-recall曲线的时候，请指定这两个指标。

您是参考这里 https://github.com/lartpang/PySODEvalToolkit#%E4%B8%80%E4%B8%AA%E5%9F%BA%E6%9C%AC%E7%9A%84%E6%89%A7%E8%A1%8C%E6%B5%81%E7%A8%8B 的示例么？我这里似乎漏了一些内容。我会把这两个指标更新上来。

**Comment by WkangLiu** [comment]
是的，我是今天下午弄得，直接复制了你的示例，对应修改的

已经看到了您最新的修改，感谢及时的回复！

**Comment by WkangLiu** [comment]
您好，我还有个问题
在我成功输出pr图后，我发现他的顺序和我dataset设置的顺序不同
我eval时候的顺序是CAMO-CHAMELEON-COD10K
但是plot后的顺序是CHAMELEON-CAMO-COD10K

新的顺序貌似是按照metric大小递减了，这个是代码中默认的嘛？

**Comment by lartpang** [comment]
@WkangLiu 
这个会优先按照那个`aliases.yaml`配置文件中的顺序来。
这里您的顺序是哪个呢？

**Comment by WkangLiu** [comment]
我在昨天没有配置```aliases.yaml```文件，且并没有设置```python plot.py --alias-yaml```的```alias-yaml```这个参数，所以导致了昨天的结果。

刚才在您的提示下，已经可以正常顺序输出了

您给出的```python plot.py```示例貌似没有```--alias-yaml```参数，方便的话可以加上~

**Comment by lartpang** [comment]
@lartpang OK，我检查下，毕竟这个脚本示例是以前的版本，可能有遗漏吧。
