### ISSUE TITLE
您好OpticalFlowBasedVOS  关于您GItHub的这个代码，我想知道是哪篇论文的代码，有无网络结构图呀

### ISSUE THREAD

**Issue by qubewx** [lartpang/PySODEvalToolkit#19]
OpticalFlowBasedVOS这篇GitHub不能评论哎，感谢作者回答！

**Comment by lartpang** [comment]
@qubewx 

你好，感谢关注我的项目。这个项目是之前做Zero-shot VOS实验时使用的一份代码，其中使用了光流数据，但是这里的光流是按照彩色图像的形式使用的，提供的模型也并没有使用复杂的结构。你可以把它理解为一个简单的baseline模型。

由于现在基本用不上了，所以我将这个仓库设置成存档了，仅开放作为参考，不再维护了。
