### ISSUE TITLE
关于曲线坐标的问题

### ISSUE THREAD

**Issue by LiuMingYy** [lartpang/PySODEvalToolkit#23]
非常感谢您杰出的工作！但是我对于F-measure和E-measure的横坐标有些问题，想请教下threshold是什么意思？为什么F-measure和E-measure会随着threshold的变化而变化？

**Comment by lartpang** [comment]
@LiuMingYy 
因为这个工具对应的sod、cod类的任务，实际评估使用的预测是灰度图，而非二值图。而这些指标的计算使用的是二值图的形式。所以涉及到二值化的问题。也就涉及到了阈值选择的问题。

这样通过不同阈值（0~255共256个）划分的方式可以更直观的了解模型的真实预测的情况。
更好的预测应该具有更加二值化的预测效果，反映在曲线上，fmeasure、emeasure也应该更平直。
