### ISSUE TITLE
为什么会生成多个图例

### ISSUE THREAD

**Issue by zifeiyu-c** [lartpang/PySODEvalToolkit#24]
使用以下命令
python tools/check_path.py --method-jsons MyJson/cos_method.json --dataset-jsons MyJson/cos_dataset.json

python eval.py --method-json MyJson/cos_method.json --dataset-json MyJson/cos_dataset.json --metric-npy output/metrics.npy --curves-npy output/curves.npy

python plot.py --style-cfg MyJson/single_row_style2.yml --num-rows 2 --curves-npys output/curves.npy --mode pr --save-name output/result
出现No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.提示，并生成了多个图例。
![result](https://github.com/lartpang/PySODEvalToolkit/assets/56395947/b4d5b32a-babe-49e5-af68-893f7497f306)

**Comment by lartpang** [comment]
@zifeiyu-c 

你的指令不太合适:
```shell
python plot.py --style-cfg MyJson/single_row_style2.yml --num-rows 2 --curves-npys output/curves.npy --mode pr --save-name output/result
```

请尝试：

```shell
python plot.py --style-cfg MyJson/single_row_style2.yml --num-rows 2 --curves-npys output/curves.npy --mode pr --separated-legend --save-name output/result
```
