### ISSUE TITLE
关于想获得数据的问题

### ISSUE THREAD

**Issue by esp9999** [lartpang/PySODEvalToolkit#26]
你好，请问如果我只想获得当前训练好的模型生成的预测结果的一些指标应该怎么做呢？

**Comment by lartpang** [comment]
如果你想直接添加到自己的项目中，方便测试，可以参考这个类，核心就是初始化不同的指标，之后对每个样本的预测和真值对进行统计，最后获得最终结果：

https://github.com/lartpang/PySODMetrics/blob/d4a14e5d271623d4147ad8450fd679572dfe52f2/examples/metric_recorder.py#L147-L227

如果你想利用这个仓库进行统计的话，需要先做一些基本的配置，具体流程可以参考readme的相关章节：https://github.com/lartpang/PySODEvalToolkit?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by esp9999** [comment]
你好，非常感谢你的工作与指导。根据你的指导，我已经将metric_recoder里的关键类添加到了项目中，并已经初步可以使用。但在使用过程中遇到两个小问题。在我使用BinaryMetricRecorder()这个类进行评估时，我观察到该类支持多种测量方式。但当我使用sample_bifm这个方法时报出了以下错误：
![屏幕截图 2024-05-13 220753](https://github.com/lartpang/PySODEvalToolkit/assets/68491672/f5d261a8-7a02-4239-a331-d92cf1e53ac9)。
以及当我用MetricRecorderV2()这个类时我观察到该类是支持fm方法的，但我使用时报出一下错误：
![屏幕截图 2024-05-13 221155](https://github.com/lartpang/PySODEvalToolkit/assets/68491672/ddda1185-cbb2-4ab9-9395-d441f696b8e2)。
如果你能帮我解答，非常感谢！

**Comment by lartpang** [comment]
@esp9999 

这个脚本之前代码库更新的时候没有进行测试，并没有即使匹配最新的代码。我刚刚更新了一下，修复了这些问题。你可以再试试：

https://github.com/lartpang/PySODMetrics/blob/4b1091a474133a4dfd3b1220b63a6669c8b1e774/examples/metric_recorder.py#L156

**Comment by esp9999** [comment]
感谢帮助，问题已解决！
