### ISSUE TITLE
评估工具怎么用啊？

### ISSUE THREAD

**Issue by rookie-fb** [lartpang/PySODEvalToolkit#3]
这个工具可以给个使用教程吗？就针对rgb图像的。。
拜托了

**Comment by lartpang** [comment]
@rookie-fb 
建议您先按照 https://github.com/lartpang/PySODEvalToolkit#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
这部分内容的介绍来使用，如果有问题，请继续留言即可。
