### ISSUE TITLE
plot_results.py遇到问题

### ISSUE THREAD

**Issue by Wickyan** [lartpang/PySODEvalToolkit#7]
我似乎无论怎么调整（画布尺寸、tight_layout()还是subplots_adjust）
都没有办法得到很好的图像。
画布似乎并不会跟着子图的个数、大小变化。
图例也游走于页面之上难以控制。

![out.png](https://i.endpot.com/image/G3JF8/out.png)
![pr.png](https://i.endpot.com/image/IW2DE/pr.png)

pyplot被封装得极其精美，以至于无从下手@_@#
请教有什么解决办法。不尽感激。

**Comment by Wickyan** [comment]
已经找到解决方案
utils/recorders/curve_drawer.py
文件中29行替换为：
```python
 axes = plt.figure(figsize=(10, 8), dpi=300).subplots(
            nrows=row_num,
            ncols=math.ceil(self.num_subplots / row_num),
            sharey=self.sharey,
        )
        # self.fig = fig
        self.axes = axes.flatten()
```
不能使用
```python
fig, axes =  plt.figure(figsize=(10, 8), dpi=300).subplots(2, 4)
```
在多行多列情况下，axes仅能读出第一行。

ToDo：
- 将算法的lable竖置（计划修改legend）
- 自定义曲线颜色

**Comment by lartpang** [comment]
@Wickyan 很高兴看到您探索不同的使用方法。
其实在我的使用流程中，我不太建议直接设置这些内容（间距、画布大小等等），因为随着方法数量的增多、数据集的数量的增多，这些设置很难普遍适用。
我一般是绘制好图像，通过直接在`plt.show()`显示的图像中进行设置，具体可见该处讨论：https://github.com/lartpang/PySODEvalToolkit/pull/1#issuecomment-791123759
这样会更加灵活。当然， 如果你对于间距和边距手动调整好后，可以通过将其直接修改到脚本中（这便于重复使用）也是可以的：
https://github.com/lartpang/PySODEvalToolkit/blob/master/examples/plot_results.py#L139-L146
但是目前暂不支持对于画布大小的初始设定。因为在后期的手动调整中，难以确定具体的画布大小。如果你有比较好的能够确定画布大小的方式，欢迎指出或者提交你的修改。

另外，关于你的“TODO"：
- ”将算法的lable竖置（计划修改legend）“这一点不太理解？
- 关于修改曲线颜色：当前我直接从matplotlib中取了颜色表，这样在添加新的方法的时候直接索引就可（因为颜色表数量足够多），当然，后期我会考虑提供一个替换内置颜色表的接口，方便用户自定义颜色表。（`our_name` 指定的方法与其他不同，会自动红色加粗现实）

**Comment by lartpang** [comment]
@Wickyan 最新版本中对于图像格式的设定提供了更直接的配置方式，欢迎使用。有问题可以重开继续讨论。
