### ISSUE TITLE
单独测method，最后在合并画图？

### ISSUE THREAD

**Issue by Wickyan** [lartpang/PySODEvalToolkit#8]
您好，请问有单独测method，最后再合并画图的方法吗？

RGBD-SOD的测试数据集NJU2K中，有些顶会使用了498张，而另外一些使用了495张，普遍使用的有500张。
我想先测使用500张的methods，再调整数据集（删掉缺失的5张、2张），测试495、498的methods。

求教，能否将两次测试结果合并画图？
（e.g. 10methods + 1method 一起画图）

再次感谢。

**Comment by lartpang** [comment]
可以尝试使用 https://github.com/lartpang/PySODEvalToolkit/blob/master/tools/append_results.py 来合并两次测试的对应的曲线数据的npy文件。再用其绘图。
